version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - maartenpaauw
  labels:
  - dependencies update
  ignore:
  - dependency-name: yamllint
    versions:
    - 1.25.0
